export class PropertyDetails {
  constructor(
    public Ownerid: String,
    public OwnerProfileImg: String,
    public ownerFullName: String,
    public OwnerPhone: String,
    public ownerEmail: String,
    public ownerAddress: String,
    public id: Number,
    public Title: String,
    public NoOfBedsPerApartment: Number,
    public noOfBedsInTheRoom: Number,
    public NoOfRooms: Number,
    public noOfBathroom: Number,
    public appartmentArea: Number,
    public FloorNumber: Number,
    public city: String,
    public governorate: String,
    public Description: String,
    public street: String,
    public propertyPrice: Number,
    public hasKitchen: Boolean,
    public hasAirConditioner: Boolean,
    public hasMicrowave: Boolean,
    public hasDishWasher: Boolean,
    public hasWifi: Boolean,
    public hasRefrigerator: Boolean,
    public hasDishesAndSilverware: Boolean,
    public asParking: Boolean,
    public hasWaterHeater: Boolean,
    public hasElevator: Boolean,
    public AverageRating: Number,
    public photos: String[]
  ) {}
}
